# Generated by Django 3.2.9 on 2022-04-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20220416_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена')),
                ('is_published', models.BooleanField(default=False, verbose_name='Является опубликованым')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование курса')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена')),
                ('is_published', models.BooleanField(default=False, verbose_name='Является опубликованым')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.RemoveField(
            model_name='offerslide',
            name='is_published_landing',
        ),
        migrations.AddField(
            model_name='offerslide',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Является опубликованым'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Является опубликованым'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published_landing',
            field=models.BooleanField(default=False, verbose_name='Является опубликованым на главной странице'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена'),
        ),
    ]
