# Generated by Django 3.2.9 on 2022-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20220419_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='Является опубликованым')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сертфикат',
                'verbose_name_plural': 'Сертфикаты',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
