# Generated by Django 3.2.9 on 2022-04-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20220420_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='Является опубликованым')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Фото Галереи',
                'ordering': ['order'],
            },
        ),
    ]
