# Generated by Django 3.2.10 on 2022-05-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20220426_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
