# Generated by Django 3.2.13 on 2022-05-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_categoryservice_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category_news',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Номер телефона'),
        ),
        migrations.DeleteModel(
            name='CategoryNews',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
